### ISSUE TITLE
windows10-installer cleans up on failure

### ISSUE THREAD

**Issue by dominikholler** [kubevirt/tekton-tasks-operator#42]
**Is this a BUG REPORT or FEATURE REQUEST?**:

/kind enhancement

**What happened**:

If the pipeline https://github.com/kubevirt/tekton-tasks-operator/blob/main/data/tekton-pipelines/okd/windows10-installer.yaml fails, the temporary created artifacts, e.g. VM, is not cleaned up.

**What you expected to happen**:

If the pipeline fails, all invalid VMs, templates and PVCs are cleaned up.

**Comment by 0xFelix** [comment]
@ksimon1 Can you close this? Fixed by #72
