### ISSUE TITLE
Prometheus metrics endpoint returns `connection refused`

### ISSUE THREAD

**Issue by enp0s3** [kubevirt/tekton-tasks-operator#49]
**Is this a BUG REPORT or FEATURE REQUEST?**:
/kind bug

**What happened**:
The Prometheus endpoint `/metrics` on port `8443` is not working, returns `connection refused`

**What you expected to happen**:
To get the exposed metrics

**How to reproduce it (as minimally and precisely as possible)**:
`oc exec it ` to the operator pod, then run `curl -L -k https://localhost:8443/metrics`

**Anything else we need to know?**:

**Environment**:
- KubeVirt version (use `virtctl version`): latest
- Kubernetes version (use `kubectl version`):
- tekton-pipelines version: latest
- kubevirt-tekton-tasks version:
- Pipeline/Taskrun specification:
- PipelineRun/TaskRun specification:
- CDI version if applicable:
- Cloud provider or hardware configuration:

**Comment by ksimon1** [comment]
Closing as the PR was merged and backported
