### ISSUE TITLE
TTO does not deploy on kubernetes cluster

### ISSUE THREAD

**Issue by opokornyy** [kubevirt/tekton-tasks-operator#78]
/kind bug

**What happened**:

I tried to deploy TTO in kubernetes cluster, but it failed.

``` Error: container has runAsNonRoot and image will run as root (pod: "tekton-tasks-operator-886dbcb5f-ph68t_kubevirt(31d05a58-046a-417c-8df2-524ba612cfcf)", container: manager)```

**What you expected to happen**:

Succesfully deploy TTO.

**How to reproduce it (as minimally and precisely as possible)**:

Deploy TTO on kubernetes cluster.

**Comment by ksimon1** [comment]
Fixed by https://github.com/kubevirt/tekton-tasks-operator/pull/93
